config/routes.rb
Superawesome::Application.routes.draw do
  get "home/index"

  scope "(:locale)", :locale => /en|id|pirate/ do
    resources :adverts
    resources :home
    
    match '/:locale' => 'home#index'
    root :to => 'home#index'
  end

end

app/models/advert.rb
class Advert
  include Mongoid::Document
  field :title, :type => String
  field :teaser, :type => String
  field :description, :type => String
  field :active, :type => Boolean
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  # GET /adverts
  # GET /adverts.xml
  def index
    @adverts = Advert.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @adverts }
    end
  end

  # GET /adverts/1
  # GET /adverts/1.xml
  def show
    @advert = Advert.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @advert }
    end
  end

  # GET /adverts/new
  # GET /adverts/new.xml
  def new
    @advert = Advert.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @advert }
    end
  end

  # GET /adverts/1/edit
  def edit
    @advert = Advert.find(params[:id])
  end

  # POST /adverts
  # POST /adverts.xml
  def create
    @advert = Advert.new(params[:advert])

    respond_to do |format|
      if @advert.save
        format.html { redirect_to(@advert, :notice => 'Advert was successfully created.') }
        format.xml  { render :xml => @advert, :status => :created, :location => @advert }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @advert.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /adverts/1
  # PUT /adverts/1.xml
  def update
    @advert = Advert.find(params[:id])

    respond_to do |format|
      if @advert.update_attributes(params[:advert])
        format.html { redirect_to(@advert, :notice => 'Advert was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @advert.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /adverts/1
  # DELETE /adverts/1.xml
  def destroy
    @advert = Advert.find(params[:id])
    @advert.destroy

    respond_to do |format|
      format.html { redirect_to(adverts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale
  
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    flash[:notice] = t(:hello_flash)
  end

end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/adverts/_form.html.haml
- simple_form_for(@advert) do |f|
	- if @advert.errors.any?
		#error_explanation
			%h2
				= pluralize(@advert.errors.count, "error")
				prohibited this advert from being saved:

			%ul
				- @advert.errors.full_messages.each do |msg|
					%li= msg

	= f.input :title
	= f.input :teaser
	= f.input :description, :as => :text
	= f.input :active, :as => :radio
	.actions
		= f.submit

app/views/adverts/edit.html.haml
%h1 Editing advert

= render 'form'

= link_to 'Show', @advert
|
= link_to 'Back', adverts_path

app/views/adverts/index.html.haml
%h1 Listing adverts

%table
	%tr
		%th Title
		%th Teaser
		%th Description
		%th Active
		%th
		%th
		%th
	- @adverts.each do |advert|
		%tr
			%td= advert.title
			%td= advert.teaser
			%td= advert.description
			%td= advert.active
			%td= link_to 'Show', advert
			%td= link_to 'Edit', edit_advert_path(advert)
			%td= link_to 'Destroy', advert, :confirm => 'Are you sure?', :method => :delete

%br/

= link_to 'New advert', new_advert_path

app/views/adverts/new.html.haml
%h1 New advert

= render 'form'

= link_to 'Back', adverts_path

app/views/adverts/show.html.haml
%p#notice= notice

%p
	%strong Title:
	= @advert.title
	
%p
	%strong Teaser:
	= @advert.teaser

%p
	%strong Description:
	= @advert.description
	
%p
	%strong Active:
	= @advert.active
	
= link_to 'Edit', edit_advert_path(@advert)
|
= link_to 'Back', adverts_path

app/views/home/index.html.erb
<h1><%= t(:hello_world) %></h1>
<p><%= flash[:notice] %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superawesome</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>